dist: xenial
sudo: false
language: python

branches:
  only:
    - master

matrix:
  include:
    # Main tests on supported Python versions.
    - python: 3.6
      env: DJANGO=2.2.1 TOXENV=py36 DJANGO_SETTINGS_MODULE=main.settings.development

install:
  - pip install -r requirements.txt

script:
  - pytest -s --cov-report=term-missing --cov-report=xml --cov-report=html --cov=src src/tests/
  - flake8 src
  - isort -rc -c src